project_id = "jipldlklzobiytkvxokf"

[functions.analyze-dental]
verify_jwt = false

[functions.validate-dental-view]
verify_jwt = false

[functions.enhance-dental-image]
verify_jwt = false

[functions.flow-payment]
verify_jwt = false

[functions.flow-payment-confirm]
verify_jwt = false

[functions.smile-simulation]
verify_jwt = false
